### ISSUE TITLE
feature request - load/decode an image

### ISSUE THREAD

**Issue by acidjazz** [btastic/flutter_native_image#4] opened 2018-04-03 00:18 UTC
this is a request to have something the equivalent of `decodeImage` from the [dart image package](https://pub.dartlang.org/packages/image) allowing me to load an image using native functionality so it doesn't take as long.

**Comment by btastic** [comment] 2018-04-03 06:32
Okay, so.. what is the goal of this feature request?

We can load an image into memory using native methods, but I can't return a reference or an array back to dart, since a reference would only work with native tools, and an array would mean copying the whole array in the same fashion the dart image package would do.

**Comment by acidjazz** [comment] 2018-04-03 11:27
I'm just looking for a way to get a `File` into an `Image` w/out having to isolate and wait 10 seconds, so far the only way I can see to do that is with `decodeImage()`

**Comment by btastic** [comment] 2018-04-03 16:57
Well the problem is that a ```File``` or an ```Image``` is just something that holds onto a ```List<int>``` internally. So we still have to manage the way from decoding an image on their native platforms, and transferring the bytes back to dart. 

There is no magic function that will make it go fast. Once you want the bytes within a dart object, the language (VM) will take time to copy the bytes to the dart counterpart (```List<int>```)

I am not a dart expert by any means, but thats what I read from the other repository's guys answer to the problem. Reading the bytes and copying it into an array. Thats not going to be fast, as far as I know..

**Closed** 2018-06-08 17:17 UTC
Labels: wontfix
